# Generated by Django 4.1.1 on 2022-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerbil',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(choices=[('WH', 'white'), ('GD', 'gold'), ('BLCK', 'black'), ('GR', 'grey'), ('BN', 'brown')], max_length=5)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=2)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
